import { AutomotiveVehicle, GalleryItem, LeaderboardEntry, RCLeaderboardEntry } from "@/types";

export const mediaConfig = {
  videos: {
    hero: "https://assets.mixkit.co/videos/preview/mixkit-car-racing-on-a-racetrack-41617-large.mp4",
    karting: "https://assets.mixkit.co/videos/preview/mixkit-go-kart-race-in-the-sunset-41620-large.mp4",
    rcRacing: "https://assets.mixkit.co/videos/preview/mixkit-small-remote-control-car-moving-on-dirt-41623-large.mp4",
    restaurant: "https://assets.mixkit.co/videos/preview/mixkit-chef-plating-a-dish-in-a-restaurant-41628-large.mp4",
    events: "https://assets.mixkit.co/videos/preview/mixkit-celebration-at-a-luxurious-venue-41630-large.mp4",
    automotive: "https://assets.mixkit.co/videos/preview/mixkit-supercar-accelerating-on-asphalt-41633-large.mp4",
    destinationNight: "https://assets.mixkit.co/videos/preview/mixkit-illuminated-night-circuit-city-view-41638-large.mp4",
    liveStream: "https://assets.mixkit.co/videos/preview/mixkit-go-kart-race-in-the-sunset-41620-large.mp4",
  },
  posters: {
    hero: "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?q=80&w=1920&auto=format&fit=crop",
    karting: "https://images.unsplash.com/photo-1547949003-9792a18a2601?q=80&w=1600&auto=format&fit=crop",
    rcRacing: "https://images.unsplash.com/photo-1581235720704-06d3acfcb36f?q=80&w=1600&auto=format&fit=crop",
    restaurant: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?q=80&w=1600&auto=format&fit=crop",
    events: "https://images.unsplash.com/photo-1511795409834-ef04bbd61622?q=80&w=1600&auto=format&fit=crop",
    automotive: "https://images.unsplash.com/photo-1617814076367-b759c7d7e738?q=80&w=1600&auto=format&fit=crop",
    destinationNight: "https://images.unsplash.com/photo-1509228468518-180dd4864904?q=80&w=1920&auto=format&fit=crop",
  },
  vehicles: [
    {
      id: "apex-gtx",
      name: "APEX GT-X ELECTRIC KART",
      category: "Motorsport Spec",
      power: "15 kW Dual Motors",
      topSpeed: "85 km/h (Governed)",
      acceleration: "0-60 in 2.9s",
      chassis: "Tubular Chromoly Competition Frame",
      brakes: "Hydraulic Dual-Vented Disc System",
      image: "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?q=80&w=1200&auto=format&fit=crop",
      desc: "Engineered with instantaneous electric torque delivery, push-to-pass digital boost, and RFID telemetry.",
    },
    {
      id: "pro-rc-18",
      name: "PRO-SCALE RC BUGGY 1:8",
      category: "RC Competition",
      power: "Brushless 2200KV Motor",
      topSpeed: "70 km/h",
      acceleration: "Instant Proportional",
      chassis: "4mm 7075 Aluminum Plate",
      brakes: "Dual Metal Disc System",
      image: "https://images.unsplash.com/photo-1581235720704-06d3acfcb36f?q=80&w=1200&auto=format&fit=crop",
      desc: "Championship scale buggy tuned for multi-surface chicanes and elevated crossover jumps.",
    },
    {
      id: "vr-hydraulic",
      name: "6-DOF HYDRAULIC RACING RIG",
      category: "Virtual Reality Simulator",
      power: "Hexapod Electric Actuators",
      topSpeed: "Infinite Virtual Spec",
      acceleration: "2.5G Surge & Sway Force",
      chassis: "FIA-Certified Bucket Cockpit",
      brakes: "Load Cell Pedals (100kg)",
      image: "https://images.unsplash.com/photo-1622979135225-d2ba269bc1df?q=80&w=1200&auto=format&fit=crop",
      desc: "Simulates real vehicle dynamics, tire slip angle, and track kerb vibrations with zero latency.",
    },
  ] as AutomotiveVehicle[],
  gallery: [
    {
      id: "g1",
      title: "Night Karting Apex",
      category: "GO-KARTING",
      type: "image",
      src: "https://images.unsplash.com/photo-1547949003-9792a18a2601?q=80&w=1200&auto=format&fit=crop",
      alt: "Go-kart rounding track hairpin at high speed",
      aspect: "landscape",
    },
    {
      id: "g2",
      title: "360° Sky Horizon Deck",
      category: "RESTAURANT",
      type: "image",
      src: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?q=80&w=1200&auto=format&fit=crop",
      alt: "Panoramic elevated dining overlooking destination",
      aspect: "landscape",
    },
    {
      id: "g3",
      title: "Custom RC Buggy Precision",
      category: "RC RACING",
      type: "image",
      src: "https://images.unsplash.com/photo-1581235720704-06d3acfcb36f?q=80&w=1200&auto=format&fit=crop",
      alt: "RC scale race car on competition raceway",
      aspect: "square",
    },
    {
      id: "g4",
      title: "Grand Banquet Hall Ambience",
      category: "EVENTS",
      type: "image",
      src: "https://images.unsplash.com/photo-1511795409834-ef04bbd61622?q=80&w=1200&auto=format&fit=crop",
      alt: "Sprawling luxury wedding and banquet ballroom",
      aspect: "portrait",
    },
    {
      id: "g5",
      title: "Automotive Heritage Showcase",
      category: "AUTOMOTIVE",
      type: "image",
      src: "https://images.unsplash.com/photo-1617814076367-b759c7d7e738?q=80&w=1200&auto=format&fit=crop",
      alt: "Hypercar showcase on illuminated turntable",
      aspect: "landscape",
    },
    {
      id: "g6",
      title: "Full-Motion VR Simulation Rigs",
      category: "SIMULATOR",
      type: "image",
      src: "https://images.unsplash.com/photo-1622979135225-d2ba269bc1df?q=80&w=1200&auto=format&fit=crop",
      alt: "Immersive VR simulator pod gaming",
      aspect: "landscape",
    },
  ] as GalleryItem[],
  leaderboard: [
    { rank: 1, driver: "Vikram R.", kart: "GT-X Electric #07", lapTime: "31.428s", gap: "Leader", date: "Today" },
    { rank: 2, driver: "Ananya M.", kart: "GT-X Electric #12", lapTime: "31.890s", gap: "+0.462s", date: "Today" },
    { rank: 3, driver: "Karthik S.", kart: "GT-X Electric #04", lapTime: "32.105s", gap: "+0.677s", date: "Yesterday" },
    { rank: 4, driver: "Rohan D.", kart: "GT-X Electric #09", lapTime: "32.441s", gap: "+1.013s", date: "2 days ago" },
    { rank: 5, driver: "Sneha P.", kart: "GT-X Electric #02", lapTime: "32.880s", gap: "+1.452s", date: "3 days ago" },
  ] as LeaderboardEntry[],
  rcLeaderboard: [
    { rank: 1, racer: "GhostRider_99", car: "Apex Buggy Pro", lapTime: "12.340s", points: 250 },
    { rank: 2, racer: "TurboDrift_KA", car: "Cyber Truggy 1:8", lapTime: "12.810s", points: 220 },
    { rank: 3, racer: "SpeedyBlaze", car: "Nitro Scale Special", lapTime: "13.102s", points: 195 },
    { rank: 4, racer: "CircuitMaster", car: "Apex Buggy Pro", lapTime: "13.450s", points: 180 },
  ] as RCLeaderboardEntry[],
  packages: [
    {
      id: "pkg-speed-savor",
      name: "SPEED & SAVOR DUO",
      tagline: "High-Octane Racing & Horizon Dining",
      badge: "MOST POPULAR",
      description: "Experience 2 thrilling electric karting sessions followed by 4-course curated dinner at 360° Sky Dining.",
      features: [
        "2x 15-Minute Electric Karting Heats",
        "RFID Telemetry Lap Printout & Video",
        "Reserved Table at 360° Sky Dining",
        "Chef's Signature Welcome Mocktail",
      ],
    },
    {
      id: "pkg-grand-prix-squad",
      name: "GRAND PRIX SQUAD",
      tagline: "Full Track Takeover for Groups & Teams",
      badge: "GROUP PASS",
      description: "Exclusive mini-tournament format with practice, qualifying, and podium flag-off for up to 10 drivers.",
      features: [
        "Exclusive Track Grid Allocation (30 Mins)",
        "Trophy & Podium Ceremony Celebration",
        "RC Arena Access & VR Simulator Passes",
        "Dedicated VIP Lounge Seating",
      ],
    },
    {
      id: "pkg-apex-all-access",
      name: "APEX ALL-ACCESS VIP",
      tagline: "Unlimited Multi-Zone Immersion",
      badge: "VIP EXPERIENCE",
      description: "Full day pass with priority pit lane queue, all simulator rigs, scale RC buggies, and private dining pod.",
      features: [
        "Priority Pit-Lane Queue on All Heats",
        "Unlimited VR Hydraulic Simulator Time",
        "Pro RC Competition Car Session",
        "Private VIP Dining Pod Reservation",
      ],
    },
  ],
  safetyHighlights: [
    { title: "24/7 Operations Protocol", desc: "Round-the-clock entertainment with dedicated quiet maintenance window from 4 AM to 7 AM." },
    { title: "HD CCTV & Telemetry Tracking", desc: "Over 120 high-definition cameras monitoring track sectors, pit lanes, and dining decks." },
    { title: "Secure Lockers & Changing Paddock", desc: "Biometric personal storage lockers, driver suites, and sanitized gear dispensaries." },
    { title: "EV Charging Infrastructure", desc: "10x Fast DC charging stalls supporting all major four-wheeler and two-wheeler EV standards." },
    { title: "FIA-Standard Safety Barriers", desc: "Polymer shock-absorbing barrier system with remote electronic emergency kart shut-off." },
    { title: "Zero Direct Emissions", desc: "100% electric motorsport fleet delivering high torque performance without fumes or oil residue." },
  ],
  kidzExperiences: [
    {
      title: "Cadet Electric Mini-Karts",
      age: "Ages 5 – 12",
      desc: "Speed-governed 15 km/h electric karts on dedicated padded circuit with remote kill-switch safety.",
      image: "https://images.unsplash.com/photo-1547949003-9792a18a2601?q=80&w=800&auto=format&fit=crop",
    },
    {
      title: "Junior RC Arena Academy",
      age: "Ages 4+",
      desc: "Beginner-friendly 1:16 scale remote control cars on illuminated multi-tier tracks with pilot instruction.",
      image: "https://images.unsplash.com/photo-1581235720704-06d3acfcb36f?q=80&w=800&auto=format&fit=crop",
    },
    {
      title: "VR Motion Playzone",
      age: "All Ages",
      desc: "Immersive family VR racing simulators, motion pods, and interactive arcade gaming with spot prizes.",
      image: "https://images.unsplash.com/photo-1622979135225-d2ba269bc1df?q=80&w=800&auto=format&fit=crop",
    },
  ],
};
