import { AutomotiveVehicle, GalleryItem, LeaderboardEntry, RCLeaderboardEntry } from "@/types";

export const mediaConfig = {
  videos: {
    hero: "https://assets.mixkit.co/videos/preview/mixkit-car-racing-on-a-racetrack-41617-large.mp4",
    karting: "https://assets.mixkit.co/videos/preview/mixkit-go-kart-race-in-the-sunset-41620-large.mp4",
    rcRacing: "https://assets.mixkit.co/videos/preview/mixkit-small-remote-control-car-moving-on-dirt-41623-large.mp4",
    restaurant: "https://assets.mixkit.co/videos/preview/mixkit-chef-plating-a-dish-in-a-restaurant-41628-large.mp4",
    events: "https://assets.mixkit.co/videos/preview/mixkit-celebration-at-a-luxurious-venue-41630-large.mp4",
    automotive: "https://assets.mixkit.co/videos/preview/mixkit-supercar-accelerating-on-asphalt-41633-large.mp4",
    destinationNight: "https://assets.mixkit.co/videos/preview/mixkit-illuminated-night-circuit-city-view-41638-large.mp4",
    liveStream: "https://assets.mixkit.co/videos/preview/mixkit-car-races-on-a-curved-track-41619-large.mp4",
  },
  posters: {
    hero: "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?q=80&w=1920&auto=format&fit=crop",
    karting: "https://images.unsplash.com/photo-1547949003-9792a18a2601?q=80&w=1600&auto=format&fit=crop",
    rcRacing: "https://images.unsplash.com/photo-1581235720704-06d3acfcb36f?q=80&w=1600&auto=format&fit=crop",
    restaurant: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?q=80&w=1600&auto=format&fit=crop",
    events: "https://images.unsplash.com/photo-1511795409834-ef04bbd61622?q=80&w=1600&auto=format&fit=crop",
    automotive: "https://images.unsplash.com/photo-1617814076367-b759c7d7e738?q=80&w=1600&auto=format&fit=crop",
    destinationNight: "https://images.unsplash.com/photo-1509228468518-180dd4864904?q=80&w=1920&auto=format&fit=crop",
    kidzZone: "https://images.unsplash.com/photo-1566492031773-4f4e44671857?q=80&w=1600&auto=format&fit=crop",
    rcBoat: "https://images.unsplash.com/photo-1559136555-9303baea8ebd?q=80&w=1600&auto=format&fit=crop",
    rcTank: "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?q=80&w=1600&auto=format&fit=crop",
    rcPlane: "https://images.unsplash.com/photo-1508614589041-895b88991e3e?q=80&w=1600&auto=format&fit=crop",
    fpvCar: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=1600&auto=format&fit=crop",
  },
  rcExperiences: [
    {
      id: "rc-track",
      title: "Championship RC Track",
      badge: "Scale 1:8 & 1:10",
      description: "Dedicated off-road and banked asphalt raceways with computer-synced transponder timing for kids & adults.",
      features: ["Multi-Surface Dirt & Asphalt", "Live Transponder Timing", "Kids & Pro Driver Categories"],
      image: "https://images.unsplash.com/photo-1581235720704-06d3acfcb36f?q=80&w=1000&auto=format&fit=crop",
    },
    {
      id: "rc-vr-gaming",
      title: "RC Virtual Gaming Zone",
      badge: "Simulated Telemetry",
      description: "Next-gen simulator cockpit combining real scale RC vehicle handling with immersive digital track feedback.",
      features: ["Real-time RC Telemetry", "Haptic Steering Pods", "Virtual Track Overlays"],
      image: "https://images.unsplash.com/photo-1622979135225-d2ba269bc1df?q=80&w=1000&auto=format&fit=crop",
    },
    {
      id: "rc-fpv-feed",
      title: "Half-Road FPV Onboard Cam",
      badge: "Cockpit Camera Feed",
      description: "Experience the adrenaline of high-speed racing through direct HD video streaming straight from the car's cockpit.",
      features: ["Zero-Latency FPV Goggles", "Driver View Racing", "Live Stream Recording"],
      image: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=1000&auto=format&fit=crop",
    },
    {
      id: "rc-boat",
      title: "RC High-Speed Boat Basin",
      badge: "Hydro Dynamics",
      description: "Rapid water circuit featuring twin-motor hydroplanes, water gates, and timed buoy navigation challenges.",
      features: ["Aquatic Circuit", "Twin-Brushless Speedboats", "Night Illuminated Buoys"],
      image: "https://images.unsplash.com/photo-1559136555-9303baea8ebd?q=80&w=1000&auto=format&fit=crop",
    },
    {
      id: "rc-tank",
      title: "RC Tank Combat Arena",
      badge: "Tactical Laser Ops",
      description: "Tactical obstacle battlefield with infrared laser-tag combat, smoke effects, and team-based assault missions.",
      features: ["Infrared Hit Sensors", "Terrain Obstacles & Bunkers", "Team Domination Modes"],
      image: "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?q=80&w=1000&auto=format&fit=crop",
    },
    {
      id: "rc-plane",
      title: "RC Plane & Aviation Zone",
      badge: "Aero Flight Simulator",
      description: "Precision aerobatics testing ground and dual-stick flight arena engineered for RC aircraft enthusiasts.",
      features: ["Flight Sim Training Rig", "High-Ceiling Flight Hangar", "Scale Micro Jets & Gliders"],
      image: "https://images.unsplash.com/photo-1508614589041-895b88991e3e?q=80&w=1000&auto=format&fit=crop",
    },
  ],
  kidzExperiences: [
    {
      title: "Junior Electric Cadet Karting",
      age: "Ages 6 – 13",
      desc: "Speed-governed karts on a cushioned safety raceway with full marshal guidance and youth-fit safety gear.",
      image: "https://images.unsplash.com/photo-1566492031773-4f4e44671857?q=80&w=800&auto=format&fit=crop",
    },
    {
      title: "Kids RC Explorer Raceway",
      age: "Ages 4+",
      desc: "Easy-control buggies with anti-collision foam bumpers and interactive light-up gate challenges.",
      image: "https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?q=80&w=800&auto=format&fit=crop",
    },
    {
      title: "Interactive Play & Simulator Pods",
      age: "All Ages",
      desc: "Engaging interactive automotive games, racing simulators, and safe arcade adventures for kids and families.",
      image: "https://images.unsplash.com/photo-1511512578047-dfb367046420?q=80&w=800&auto=format&fit=crop",
    },
  ],
  packages: [
    {
      id: "day-out",
      name: "Day Out Discovery Pass",
      tagline: "The Full Destination Immersion",
      description: "Perfect for thrill seekers and friends looking for a complete sprint across karting, RC arena, and sky dining.",
      features: [
        "Multiple Electric Karting Heats",
        "RC Arena Multi-Vehicle Access (Cars, Tanks, Boats)",
        "Reserved Table at 360° Sky Dining",
        "Complimentary Lockers & Helmet Gear",
      ],
      badge: "Most Popular",
    },
    {
      id: "kids-pack",
      name: "Junior Speedster Package",
      tagline: "Designed for Young Champions",
      description: "Tailored safe thrills for kids with junior karting, RC explorer circuits, and gaming pods.",
      features: [
        "Cadet Electric Karting with Marshal Briefing",
        "RC Fun Raceway & Mini Tank Challenge",
        "Kidz Zone Arcade Credits",
        "Junior Driver Certificate & Souvenir",
      ],
      badge: "Family Safe",
    },
    {
      id: "adult-pack",
      name: "Adrenaline Pro Package",
      tagline: "High-Octane Adult Experience",
      description: "Unlimited adrenaline with high-power karting heats, FPV cockpit racing, and VIP paddock perks.",
      features: [
        "Full-Power Apex GT-X Karting Sprints",
        "Half-Road FPV Headset Racing",
        "RC Tank Tactical Battle Session",
        "360° Signature Non-Alcoholic Club Lounge Access",
      ],
      badge: "Pro Adrenaline",
    },
    {
      id: "corporate-ccc",
      name: "Corporate Company Collaboration (CCC)",
      tagline: "Unrivaled Team Building & Paddock Camaraderie",
      description: "Exclusive corporate packages with private track hire, team endurance championships, and catered banquet halls.",
      features: [
        "Private Track Takeover & Timed Grand Prix",
        "Corporate Trophy Podium & Telemetry Printouts",
        "Dedicated Banquet / Conference Hall Setup",
        "Gourmet Non-Alcoholic Dining & Mocktail Bar",
      ],
      badge: "Corporate Elite",
    },
    {
      id: "esports-party",
      name: "Private eSports & Sim Party",
      tagline: "Virtual & Real Racing Mixed Arena",
      description: "Full-motion hydraulic simulator competition coupled with scale RC battles for private groups and birthdays.",
      features: [
        "6-DOF Hydraulic Simulator Tournament",
        "RC Virtual Gaming Cockpit Access",
        "Private Lounge with Live Broadcast Feed",
        "Customized Catering Experience",
      ],
      badge: "Tech & Gaming",
    },
  ],
  safetyHighlights: [
    { title: "24-Hour Operation", desc: "Round-the-clock motorsport and dining (Daily maintenance: 4:00 AM – 7:00 AM)." },
    { title: "24/7 CCTV Monitored", desc: "Comprehensive facility surveillance and marshal safety checkpoints." },
    { title: "Free Lockers & Gear", desc: "Complimentary secure lockers and sanitized professional racing helmets." },
    { title: "Free Valet & Parking", desc: "Spacious dedicated parking with electric vehicle charging stations." },
    { title: "BYO Helmet Welcome", desc: "Bring your certified helmet or use our on-site sanitized helmets." },
    { title: "Zero-Emission Electric", desc: "100% clean electric karts with zero exhaust fumes in an indoor circuit." },
  ],
  vehicles: [
    {
      id: "apex-gtx",
      name: "APEX GT-X ELECTRIC KART",
      category: "Motorsport Spec",
      power: "15 kW Dual Electric Motors",
      topSpeed: "85 km/h (Governed for Circuit)",
      acceleration: "0-60 km/h in 2.9s",
      chassis: "Tubular Chromoly Competition Frame",
      brakes: "Hydraulic Dual-Vented Disc System",
      image: "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?q=80&w=1200&auto=format&fit=crop",
      desc: "Engineered with instantaneous electric torque delivery, push-to-pass digital boost, and RFID telemetry.",
    },
    {
      id: "flux-ev-racer",
      name: "FLUX MOTORS PROTOTYPE-E",
      category: "Flux Motors India Partner Machine",
      power: "120 kW Permanent Magnet AC",
      topSpeed: "210 km/h Track Spec",
      acceleration: "0-100 km/h in 3.1s",
      chassis: "Carbon Fiber Monocoque",
      brakes: "Regenerative Carbon-Ceramic",
      image: "https://images.unsplash.com/photo-1617814076367-b759c7d7e738?q=80&w=1200&auto=format&fit=crop",
      desc: "Developed in association with Flux Motors India, demonstrating high-performance electric automotive technology.",
    },
    {
      id: "pro-rc-18",
      name: "PRO-SCALE RC BUGGY 1:8",
      category: "RC Competition",
      power: "Brushless 2200KV Motor",
      topSpeed: "70 km/h",
      acceleration: "Instant Proportional",
      chassis: "4mm 7075 Aluminum Plate",
      brakes: "Dual Metal Disc System",
      image: "https://images.unsplash.com/photo-1581235720704-06d3acfcb36f?q=80&w=1200&auto=format&fit=crop",
      desc: "Championship scale buggy tuned for multi-surface chicanes and elevated crossover jumps.",
    },
    {
      id: "vr-hydraulic",
      name: "6-DOF HYDRAULIC RACING RIG",
      category: "Virtual Reality Simulator",
      power: "Hexapod Electric Actuators",
      topSpeed: "Infinite Virtual Spec",
      acceleration: "2.5G Surge & Sway Force",
      chassis: "FIA-Certified Bucket Cockpit",
      brakes: "Load Cell Pedals (100kg)",
      image: "https://images.unsplash.com/photo-1622979135225-d2ba269bc1df?q=80&w=1200&auto=format&fit=crop",
      desc: "Simulates real vehicle dynamics, tire slip angle, and track kerb vibrations with zero latency.",
    },
  ] as AutomotiveVehicle[],
  gallery: [
    {
      id: "g1",
      title: "Night Karting Apex Circuit",
      category: "RACING",
      type: "image",
      src: "https://images.unsplash.com/photo-1547949003-9792a18a2601?q=80&w=1200&auto=format&fit=crop",
      alt: "Go-kart rounding track hairpin at high speed",
      aspect: "landscape",
    },
    {
      id: "g2",
      title: "360° Sky Horizon Deck Dining",
      category: "DINING",
      type: "image",
      src: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?q=80&w=1200&auto=format&fit=crop",
      alt: "Panoramic elevated dining overlooking destination",
      aspect: "landscape",
    },
    {
      id: "g3",
      title: "Scale 1:8 Championship RC Raceway",
      category: "RC",
      type: "image",
      src: "https://images.unsplash.com/photo-1581235720704-06d3acfcb36f?q=80&w=1200&auto=format&fit=crop",
      alt: "RC scale race car on competition raceway",
      aspect: "square",
    },
    {
      id: "g4",
      title: "Grand Celebration & Banquet Ballroom",
      category: "EVENTS",
      type: "image",
      src: "https://images.unsplash.com/photo-1511795409834-ef04bbd61622?q=80&w=1200&auto=format&fit=crop",
      alt: "Sprawling luxury wedding and banquet ballroom",
      aspect: "portrait",
    },
    {
      id: "g5",
      title: "Automotive Heritage & Flux Showcase",
      category: "AUTOMOTIVE",
      type: "image",
      src: "https://images.unsplash.com/photo-1617814076367-b759c7d7e738?q=80&w=1200&auto=format&fit=crop",
      alt: "Hypercar showcase on illuminated turntable",
      aspect: "landscape",
    },
    {
      id: "g6",
      title: "Junior Cadet Karting Arena",
      category: "RACING",
      type: "image",
      src: "https://images.unsplash.com/photo-1566492031773-4f4e44671857?q=80&w=1200&auto=format&fit=crop",
      alt: "Kidz zone junior karting safety track",
      aspect: "landscape",
    },
    {
      id: "g7",
      title: "RC Boat High Speed Basin",
      category: "RC",
      type: "image",
      src: "https://images.unsplash.com/photo-1559136555-9303baea8ebd?q=80&w=1200&auto=format&fit=crop",
      alt: "RC boat splashing on water track",
      aspect: "landscape",
    },
    {
      id: "g8",
      title: "Destination Grand Atrium by Night",
      category: "VENUE",
      type: "image",
      src: "https://images.unsplash.com/photo-1509228468518-180dd4864904?q=80&w=1200&auto=format&fit=crop",
      alt: "Night illumination of 24Ours destination exterior",
      aspect: "landscape",
    },
  ] as GalleryItem[],
  leaderboard: [
    { rank: 1, driver: "Vikram R.", kart: "APEX GT-X #07", lapTime: "31.428s", gap: "Podium P1", date: "Today" },
    { rank: 2, driver: "Ananya M.", kart: "APEX GT-X #12", lapTime: "31.890s", gap: "+0.462s", date: "Today" },
    { rank: 3, driver: "Karthik S.", kart: "APEX GT-X #04", lapTime: "32.105s", gap: "+0.677s", date: "Yesterday" },
    { rank: 4, driver: "Rohan D.", kart: "APEX GT-X #09", lapTime: "32.441s", gap: "+1.013s", date: "2 days ago" },
    { rank: 5, driver: "Sneha P.", kart: "APEX GT-X #02", lapTime: "32.880s", gap: "+1.452s", date: "3 days ago" },
    { rank: 6, driver: "Varun K.", kart: "APEX GT-X #11", lapTime: "33.012s", gap: "+1.584s", date: "3 days ago" },
    { rank: 7, driver: "Pooja N.", kart: "APEX GT-X #05", lapTime: "33.250s", gap: "+1.822s", date: "4 days ago" },
    { rank: 8, driver: "Aditya T.", kart: "APEX GT-X #08", lapTime: "33.490s", gap: "+2.062s", date: "5 days ago" },
  ] as LeaderboardEntry[],
  rcLeaderboard: [
    { rank: 1, racer: "GhostRider_99", car: "Apex Buggy Pro 1:8", lapTime: "12.340s", points: 250 },
    { rank: 2, racer: "TurboDrift_KA", car: "Cyber Truggy 1:8", lapTime: "12.810s", points: 220 },
    { rank: 3, racer: "SpeedyBlaze", car: "Nitro Scale Special", lapTime: "13.102s", points: 195 },
    { rank: 4, racer: "CircuitMaster", car: "Apex Buggy Pro 1:8", lapTime: "13.450s", points: 180 },
    { rank: 5, racer: "FPV_Phantom", car: "FPV Onboard Stealth", lapTime: "13.820s", points: 165 },
  ] as RCLeaderboardEntry[],
};

